// Единый источник данных о сборках — здесь и только здесь редактируете сборки.
//
// Чтобы добавить/изменить сборку:
// 1) Скриншот: киньте PNG/JPG в папку public/screenshots/, впишите путь в поле
//    screenshot, например: screenshot: '/screenshots/my-build.png'
// 2) Ссылка на скачивание: впишите прямую ссылку (Я.Диск, Google Drive, TG-пост
//    с файлом) в поле download, например: download: 'https://disk.yandex.ru/d/xxxx'
//    Если download не заполнен — кнопка «Скачать» на сайте ведёт в Telegram.
// 3) Цена: price: null — бесплатно, price: 200 — платно за 200 ₽.
// 4) Чтобы добавить новую сборку, скопируйте один из объектов { ... } целиком
//    и вставьте в массив ниже, поменяв поля под себя.
// После сохранения файла и деплоя изменения сразу появятся на сайте.

export type Build = {
  sky: string
  tower: { left: string; width: string; height: string }
  d1: string
  name: string
  n: string
  title: string
  tags: string[]
  desc: string
  details: string[]
  screenshot?: string
  download?: string
  price: number | null // null = бесплатно, число = цена в ₽
  downloads: number // счётчик скачиваний — меняете вручную, когда захотите обновить цифру
}

export const BUILDS: Build[] = [
  {
    sky: 'linear-gradient(180deg,#241010 0%,#3a1414 45%,#c1272d 100%)',
    tower: { left: '58%', width: '16%', height: '60%' },
    d1: '01',
    name: 'invicta own crmp',
    n: '',
    title: 'invicta own crmp!',
    tags: ['приятные тона', 'смена радара'],
    desc: 'Приятные фиолетовые тона, подходит для слабых и средних ПК, не нагружает ваш компютер, красивая графика.',
    details: [
      'Можно поменять табло капта - /capture | Смена формы радара - /radar',
      'Красивая оригинальная графика, которую можно менять /sw - смена погоды | /st - смена времени',
      'Подходит для слабых и средних ПК, не нагружает ваш компютер',
    ],
    screenshot: '/screenshots/invicta-01.png',
    download: 'https://disk.yandex.ru/d/VZ3elo6O0BwA5g',
    price: null,
    downloads: 74,
  },
  {
    sky: 'linear-gradient(180deg,#241010 0%,#3a1414 45%,#e0525a 100%)',
    tower: { left: '15%', width: '12%', height: '60%' },
    d1: '02',
    name: 'Solaigetr strong mafia!',
    n: '',
    title: 'Solaigetr strong mafia!',
    tags: ['Большой FPS', 'Смена радара'],
    desc: 'Приятная графика сделана под HUD, обновляется вместе с патчами клиента',
    details: [
      'Можно поменять табло капта - /capture | Смена формы радара - /radar',
      'Приятная графика сделана под HUD,которую можно менять /sw - смена погоды | /st - смена времени.' ,
      'Установлены старые карточки домов и бизнесов',
    ],
    screenshot: '/screenshots/solaigetr_strong.png',
    download: 'https://disk.yandex.ru/d/Kv6MuXrpmuf7BA',
    price: null,
    downloads: 45,
  },
  {
    sky: 'linear-gradient(180deg,#130808 0%,#2a1111 45%,#8f1d24 100%)',
    tower: { left: '70%', width: '10%', height: '70%' },
    d1: '03',
    name: 'hatoyama let`s take out all the opps',
    n: '',
    title: 'hatoyama out opps',
    tags: ['тёмная тема', 'огненные акценты'],
    desc: 'очень атмосферная сборка, подойдет для каптов и мувиков, красивый оранжевый кулак на фисте.',
    details: [
      'Можно поменять табло капта - /capture | Смена формы радара - /radar',
      'заменены иконки на карте,звуки на оружия,табло каптов,/sw, /st - смена времени и погоды. ',
      'Приватная версия — не встречается в открытом доступе',
    ],
    screenshot: '/screenshots/hatoyama_orng.png',
    download: 'https://t.me/nelacostework/877',
    price: 200,
    downloads: 21,
  },
  {
    sky: 'linear-gradient(180deg,#241010 0%,#3a1414 45%,#c1272d 100%)',
    tower: { left: '40%', width: '9%', height: '66%' },
    d1: '04',
    name: 'Onsomeshit the way to space',
    n: 'v8',
    title: 'Onsmsht space',
    tags: ['onsmsht', 'фиолетовые тона'],
    desc: 'Красивые фиолетовые тона, приятные звуки ганов',
    details: [
      'Можно поменять табло капта - /capture | Смена формы радара - /radar',
      'Красивая оригинальная графика, которую можно менять /sw - смена погоды | /st - смена времени',
      'Подходит для слабых и средних ПК, не нагружает ваш компютер',
    ],
    screenshot: '/screenshots/onsmshit_fiol.png',
    download: 'https://disk.yandex.ru/d/v5hVGY4s5h77CA',
    price: null,
    downloads: 43,
  },
  {
    sky: 'linear-gradient(180deg,#241010 0%,#2a1111 45%,#e0767a 100%)',
    tower: { left: '80%', width: '11%', height: '58%' },
    d1: '05',
    name: 'incide bastards',
    n: '',
    title: 'Incide your bastards',
    tags: ['красивая графика', 'крупный шрифт'],
    desc: 'Красивая атмосферная сборка, подойдет для каптов, мувиков и для повседневной игры',
    details: [
      'Крупный, легко читаемый шрифт лого-серверов',
      'Можно поменять табло капта - /capture | Смена формы радара - /radar',
      'Приятная страная графика,которую можно менять /sw - смена погоды | /st - смена времени.',
    ],
    screenshot: '/screenshots/incide_your.png',
    download: 'https://t.me/nelacostework/858',
    price: 250,
    downloads: 13,
  },
    {
    sky: 'linear-gradient(180deg,#241010 0%,#2a1111 45%,#e0767a 100%)',
    tower: { left: '80%', width: '11%', height: '58%' },
    d1: '06',
    name: 'Soulrage beatiful',
    n: '',
    title: 'Soulrage beatiful game',
    tags: ['красивая графика', 'крупный шрифт'],
    desc: 'Красивая атмосферная сборка, подойдет для каптов, мувиков и для повседневной игры',
    details: [
      'Красивое лого-серверов,старая графика с приятнымы звуками ганов. ',
      'Можно поменять табло капта - /capture | Смена формы радара - /radar',
      'Сменить графику - /sw - смена погоды | /st - смена времени. ',
    ],
    screenshot: '/screenshots/soularage_beatiful.png',
    download: 'https://disk.yandex.ru/d/kFv-2iHEBSDcaw',
    price: null,
    downloads: 51,
  },
    {
    sky: 'linear-gradient(180deg,#241010 0%,#3a1414 45%,#c1272d 100%)',
    tower: { left: '58%', width: '16%', height: '60%' },
    d1: '07',
    name: 'CATRAGE Legendary players!',
    n: '',
    title: 'CATRAGE Legendary players',
    tags: ['приятные тона', 'смена радара'],
    desc: 'Идеальная сборка для Radmir RP, повышает FPS.',
    details: [
      'Можно поменять табло капта - /capture | Смена формы радара - /radar',
      'Красивая оригинальная графика, которую можно менять /sw - смена погоды | /st - смена времени',
      'Подходит для слабых и средних ПК, не нагружает ваш компютер',
    ],
    screenshot: '/screenshots/catrage_legendary.png',
    download: 'https://disk.yandex.ru/d/MSrx1_-V7xba0g',
    price: null,
    downloads: 167,
  },
    {
    sky: 'linear-gradient(180deg,#241010 0%,#3a1414 45%,#c1272d 100%)',
    tower: { left: '58%', width: '16%', height: '60%' },
    d1: '08',
    name: 'Radmir old gta',
    n: '',
    title: 'Radmir old gta',
    tags: ['приятные тона', 'смена радара'],
    desc: 'Приятные светло оранжевые тона, подходит для слабых и средних ПК, не нагружает ваш компютер, красивая графика.',
    details: [
      'Можно поменять табло капта - /capture | Смена формы радара - /radar',
      'Приятная оранжевая оригинальная графика, которую можно менять /sw - смена погоды | /st - смена времени',
      'Старое дефолтное лого, установлены старые карточки домов и бизнесов',
    ],
    screenshot: '/screenshots/radmir_oldgta.png',
    download: 'https://disk.yandex.ru/d/tDk0tb82J5_DAA',
    price: null,
    downloads: 63,
  },
    {
    sky: 'linear-gradient(180deg,#241010 0%,#3a1414 45%,#c1272d 100%)',
    tower: { left: '58%', width: '16%', height: '60%' },
    d1: '09',
    name: 'Onsomeshit legends remain',
    n: '',
    title: 'Onsomeshit legends remain',
    tags: ['приятные тона', 'смена радара'],
    desc: 'Приятные серые тона, подходит для слабых и средних ПК, не нагружает ваш компютер, красивая графика.',
    details: [
      'Можно поменять табло капта - /capture | Смена формы радара - /radar',
      'Красивая оригинальная графика, которую можно менять /sw - смена погоды | /st - смена времени',
      'Подходит для слабых и средних ПК, не нагружает ваш компютер и установлены старые карточки домов и бизнесов',
    ],
    screenshot: '/screenshots/onsmshit_legendremain.png',
    download: 'https://disk.yandex.ru/d/yfDvwbws_mfOTQ',
    price: null,
    downloads: 25,
  },
    {
    sky: 'linear-gradient(180deg,#241010 0%,#3a1414 45%,#c1272d 100%)',
    tower: { left: '58%', width: '16%', height: '60%' },
    d1: '10',
    name: 'Onsomeshit the cult generation!',
    n: '',
    title: 'Onsomeshit cult two',
    tags: ['Ориг графа', 'Смена табла каптов'],
    desc: 'Оригинальная графика, старые карточки бизов/домов.',
    details: [
      'Можно поменять табло капта - /capture | Смена формы радара - /radar',
      'Красивая оригинальная графика, которую можно менять /sw - смена погоды | /st - смена времени',
      'Подходит для слабых и средних ПК, не нагружает ваш компютер',
    ],
    screenshot: '/screenshots/onsmsht_culttwo.png',
    download: 'https://t.me/nelacostework/820',
    price: null,
    downloads: 56,
  },
    {
    sky: 'linear-gradient(180deg,#241010 0%,#3a1414 45%,#c1272d 100%)',
    tower: { left: '58%', width: '16%', height: '60%' },
    d1: '11',
    name: 'External the scariets dark streets!',
    n: '',
    title: 'extrnl dark streets',
    tags: ['приятные тона', 'смена радара'],
    desc: 'Красивый HUD в оранжевых тонах. С приятной графикой.',
    details: [
      'Можно поменять табло капта - /capture | Смена формы радара - /radar',
      'Красивая оригинальная графика, которую можно менять /sw - смена погоды | /st - смена времени',
      'Подходит для слабых и средних ПК, не нагружает ваш компютер',
    ],
    screenshot: '/screenshots/external_the.png',
    download: 'https://disk.yandex.ru/d/AZf5jo4a9kPkKQ',
    price: null,
    downloads: 124,
  },
      {
    sky: 'linear-gradient(180deg,#241010 0%,#3a1414 45%,#c1272d 100%)',
    tower: { left: '58%', width: '16%', height: '60%' },
    d1: '12',
    name: 'invicta own crmp',
    n: '',
    title: 'invicta own crmp!',
    tags: ['приятные тона', 'смена радара'],
    desc: 'Приятные фиолетовые тона, подходит для слабых и средних ПК, не нагружает ваш компютер, красивая графика.',
    details: [
      'Можно поменять табло капта - /capture | Смена формы радара - /radar',
      'Красивая оригинальная графика, которую можно менять /sw - смена погоды | /st - смена времени',
      'Подходит для слабых и средних ПК, не нагружает ваш компютер',
    ],
    screenshot: '/screenshots/nelacoste_ww.png',
    download: 'https://disk.yandex.ru/d/Fx-chhYUnP9N3Q',
    price: null,
    downloads: 124,
  },
    {
    sky: 'linear-gradient(180deg,#241010 0%,#3a1414 45%,#c1272d 100%)',
    tower: { left: '58%', width: '16%', height: '60%' },
    d1: '11',
    name: 'Whiterz gta',
    n: '',
    title: 'Whiterz gta',
    tags: ['приятные тона', 'смена радара'],
    desc: 'Приятные фиолетовые тона, подходит для слабых и средних ПК, не нагружает ваш компютер, красивая графика.',
    details: [
      'Можно поменять табло капта - /capture | Смена формы радара - /radar',
      'Красивая оригинальная графика, которую можно менять /sw - смена погоды | /st - смена времени',
      'Подходит для слабых и средних ПК, не нагружает ваш компютер',
    ],
    screenshot: '/screenshots/whiterz_top.png',
    download: 'https://disk.yandex.ru/d/bYXjCJxoy5eZTA',
    price: null,
    downloads: 124,
  },
      {
    sky: 'linear-gradient(180deg,#241010 0%,#3a1414 45%,#c1272d 100%)',
    tower: { left: '58%', width: '16%', height: '60%' },
    d1: '11',
    name: 'Exshade own the night!',
    n: '',
    title: 'Exshade night',
    tags: ['приятные тона', 'смена радара'],
    desc: 'Приятные тона, подходит для слабых и средних ПК, не нагружает ваш компютер, красивая графика.',
    details: [
      'Можно поменять табло капта - /capture | Смена формы радара - /radar',
      'Красивая оригинальная графика, которую можно менять /sw - смена погоды | /st - смена времени',
      'Подходит для слабых и средних ПК, не нагружает ваш компютер',
    ],
    screenshot: '/screenshots/exshade_mpav.png',
    download: 'https://disk.yandex.ru/d/9wumty6ohWg8xg',
    price: null,
    downloads: 367,
  },
      {
    sky: 'linear-gradient(180deg,#241010 0%,#3a1414 45%,#c1272d 100%)',
    tower: { left: '58%', width: '16%', height: '60%' },
    d1: '11',
    name: 'Exuberand the coolest guy',
    n: '',
    title: 'Exuberand coolest',
    tags: ['приятные тона', 'смена радара'],
    desc: 'Приятные тона, подходит для слабых и средних ПК, не нагружает ваш компютер, красивая графика.',
    details: [
      'Можно поменять табло капта - /capture | Смена формы радара - /radar',
      'Красивая оригинальная графика, которую можно менять /sw - смена погоды | /st - смена времени',
      'Подходит для слабых и средних ПК, не нагружает ваш компютер',
    ],
    screenshot: '/screenshots/exuberant_thecolest.png',
    download: 'https://disk.yandex.ru/d/0PuXZQLm6IIsaQ',
    price: null,
    downloads: 43,
  },
   {
    sky: 'linear-gradient(180deg,#241010 0%,#3a1414 45%,#c1272d 100%)',
    tower: { left: '58%', width: '16%', height: '60%' },
    d1: '11',
    name: 'Butterfly gta',
    n: '',
    title: 'Бабочка gta',
    tags: ['приятные тона', 'смена радара/табла'],
    desc: 'Приятные серые тона, подходит для слабых и средних ПК, не нагружает ваш компютер, красивая графика.',
    details: [
      'Можно поменять табло капта - /capture | Смена формы радара - /radar',
      'Красивая оригинальная графика, которую можно менять /sw - смена погоды | /st - смена времени',
      'Подходит для слабых и средних ПК, не нагружает ваш компютер',
    ],
    screenshot: '/screenshots/babochka_gta.png',
    download: 'https://disk.yandex.ru/d/oFaIPtwjadSbyQ',
    price: null,
    downloads: 53,
  },
   {
    sky: 'linear-gradient(180deg,#241010 0%,#3a1414 45%,#c1272d 100%)',
    tower: { left: '58%', width: '16%', height: '60%' },
    d1: '11',
    name: 'exuberant the owners this street',
    n: '',
    title: 'exuberant GTA ',
    tags: ['приятные тона', 'смена радара'],
    desc: 'Очень приятная графика, подходит для слабых и средних ПК, не нагружает ваш компютер, красивая графика.',
    details: [
      'Можно поменять табло капта - /capture | Смена формы радара - /radar',
      'Красивая оригинальная графика, которую можно менять /sw - смена погоды | /st - смена времени',
      'Подходит для слабых и средних ПК, не нагружает ваш компютер',
    ],
    screenshot: '/screenshots/exuberant_street.png',
    download: 'https://disk.yandex.ru/d/ozBa9RNjX4inJg',
    price: null,
    downloads: 51,
  },
   {
    sky: 'linear-gradient(180deg,#241010 0%,#3a1414 45%,#c1272d 100%)',
    tower: { left: '58%', width: '16%', height: '60%' },
    d1: '11',
    name: 'Godeless GTA',
    n: '',
    title: 'Godeless GTA',
    tags: ['приятные тона', 'смена радара'],
    desc: 'Приятные серые тона, подходит для слабых и средних ПК, не нагружает ваш компютер, красивая графика.',
    details: [
      'Можно поменять табло капта - /capture | Смена формы радара - /radar',
      'Красивая оригинальная графика, которую можно менять /sw - смена погоды | /st - смена времени',
      'Подходит для слабых и средних ПК, не нагружает ваш компютер',
    ],
    screenshot: '/screenshots/godeles_whinte.png',
    download: 'https://disk.yandex.ru/d/PIWcOqluNeVyrA',
    price: null,
    downloads: 297,
  },
     {
    sky: 'linear-gradient(180deg,#241010 0%,#3a1414 45%,#c1272d 100%)',
    tower: { left: '58%', width: '16%', height: '60%' },
    d1: '11',
    name: 'Berezki gta',
    n: '',
    title: 'Berezki gta',
    tags: ['приятные тона', 'смена радара'],
    desc: 'Приятные светлые тона худа, подходит для слабых и средних ПК, не нагружает ваш компютер, красивая графика.',
    details: [
      'Можно поменять табло капта - /capture | Смена формы радара - /radar',
      'Красивая оригинальная графика, которую можно менять /sw - смена погоды | /st - смена времени',
      'Подходит для слабых и средних ПК, не нагружает ваш компютер',
    ],
    screenshot: '/screenshots/berezki_gta.png',
    download: 'https://disk.yandex.ru/d/6J4e0iMr_LIvhg',
    price: null,
    downloads: 23,
  },
       {
    sky: 'linear-gradient(180deg,#241010 0%,#3a1414 45%,#c1272d 100%)',
    tower: { left: '58%', width: '16%', height: '60%' },
    d1: '11',
    name: 'Hatoyama wizards are the coolest!',
    n: '',
    title: 'Hatoyama wizards',
    tags: ['приятные тона', 'смена радара'],
    desc: 'Приятные фиолетовые тона худа, подходит для слабых и средних ПК, не нагружает ваш компютер, красивая графика.',
    details: [
      'Можно поменять табло капта - /capture | Смена формы радара - /radar',
      'Красивая оригинальная графика, которую можно менять /sw - смена погоды | /st - смена времени',
      'Подходит для слабых и средних ПК, не нагружает ваш компютер',
    ],
    screenshot: '/screenshots/hatoyama_wizards_are_the_coolest.png',
    download: 'https://disk.yandex.ru/d/Fb1fSq7i-sQ9Zw',
    price: null,
    downloads: 19,
  },
    {
    sky: 'linear-gradient(180deg,#241010 0%,#3a1414 45%,#c1272d 100%)',
    tower: { left: '58%', width: '16%', height: '60%' },
    d1: '11',
    name: 'External all the small things!',
    n: '',
    title: 'external gta',
    tags: ['приятные тона', 'смена радара'],
    desc: 'Приятные серые тона худа, подходит для слабых и средних ПК, не нагружает ваш компютер, красивая графика.',
    details: [
      'Можно поменять табло капта - /capture | Смена формы радара - /radar',
      'Красивая оригинальная графика, которую можно менять /sw - смена погоды | /st - смена времени',
      'Подходит для слабых и средних ПК, не нагружает ваш компютер',
    ],
    screenshot: '/screenshots/external_small.png',
    download: 'https://disk.yandex.ru/d/DJWl_cvKq4JpZw',
    price: null,
    downloads: 43,
  },
]
